# Generated by Django 3.1.2 on 2020-12-01 19:49

from django.db import migrations, models
import jobPortal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200, verbose_name='Title')),
                ('salary', models.CharField(max_length=100, verbose_name='Salary')),
                ('qualification', models.CharField(max_length=200, verbose_name='Qualification')),
                ('work_hours', models.CharField(max_length=200, verbose_name='Work Hours')),
                ('description', models.TextField(blank=True, default='')),
                ('company_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Company Name')),
                ('contact_person', models.CharField(max_length=50, verbose_name='Contact Person')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('mobile', models.CharField(default='', help_text='Mobile Number(10 digits) ', max_length=10)),
                ('whatsapp', models.CharField(blank=True, default='', help_text='WhatsApp Number(10 digits) ', max_length=10)),
                ('location', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=50)),
                ('state', models.CharField(blank=True, default='Bihar', max_length=50)),
                ('date_added', models.TimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('sticky', models.BooleanField(default=False)),
                ('whatsapp_active', models.BooleanField(default=True)),
                ('job_image', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d ', validators=[jobPortal.models.validate_image], verbose_name='Job Image')),
            ],
        ),
    ]
