# Generated by Django 3.1.2 on 2020-12-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPortal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
