# Generated by Django 3.1.2 on 2020-11-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Product')),
                ('seller_name', models.CharField(max_length=50, verbose_name='Seller Name')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('mobile', models.CharField(blank=True, default='', max_length=15)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('city', models.CharField(blank=True, default='', max_length=50)),
                ('state', models.CharField(blank=True, default='Bihar', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('date_added', models.TimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('whatsapp_active', models.BooleanField(default=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d ', verbose_name='Product Image')),
            ],
        ),
    ]
