# Generated by Django 3.1.2 on 2020-11-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleitem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sticky',
            field=models.BooleanField(default=False),
        ),
    ]
