# Generated by Django 3.1.2 on 2020-11-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleitem', '0002_auto_20201128_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='whatsapp',
            field=models.CharField(blank=True, default='', help_text='WhatsApp Number(10 digits) ', max_length=10),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='mobile',
            field=models.CharField(default='', help_text='Mobile Number(10 digits) ', max_length=10),
        ),
    ]
