# Generated by Django 3.1.2 on 2020-12-01 19:49

from django.db import migrations, models
import saleitem.models


class Migration(migrations.Migration):

    dependencies = [
        ('saleitem', '0003_auto_20201129_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d ', validators=[saleitem.models.validate_image], verbose_name='Product Image'),
        ),
    ]
