# Generated by Django 3.1.2 on 2020-12-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleitem', '0004_auto_20201202_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
