# Generated by Django 3.1.2 on 2020-12-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleitem', '0005_auto_20201205_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
