# # Generated by Django 2.0.8 on 2020-11-23 19:59

from django.db import migrations, models
import django.db.models.deletion
import member.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=50, null=True, verbose_name='District')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('enterprise_name', models.CharField(blank=True, max_length=70, null=True, verbose_name='Enterprise Name')),
                ('figure', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d ', validators=[member.models.validate_image], verbose_name='Member Image')),
                ('mobile_number', models.CharField(max_length=10, unique=True, verbose_name='Mobile Number')),
                ('whatsapp_number', models.CharField(blank=True, max_length=10, verbose_name='WhatsApp Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=70, verbose_name='Address')),
                ('pin_code', models.CharField(blank=True, max_length=6, verbose_name='Pin Code')),
                ('comments', models.TextField(blank=True, null=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.District', verbose_name='District')),
                ('products', models.ManyToManyField(blank=True, to='product.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'permissions': (('view_members', 'View Members'),),
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='State')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.State', verbose_name='State'),
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.State', verbose_name='State'),
        ),
    ]
