# Generated by Django 2.0.8 on 2020-11-23 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20201124_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.State', verbose_name='State'),
        ),
        migrations.AddField(
            model_name='member',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.State', verbose_name='State'),
        ),
    ]
