# Generated by Django 2.0.8 on 2020-11-23 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20201124_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='figure',
        ),
    ]
