# Generated by Django 2.0.8 on 2020-11-23 20:49

from django.db import migrations, models
import member.models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_remove_member_figure'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='figure',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d ', validators=[member.models.validate_image], verbose_name='Member Image'),
        ),
    ]
