# Generated by Django 3.1.2 on 2020-12-25 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(help_text='Plan Identifier/Name', max_length=20)),
                ('bigha', models.IntegerField(default=0, help_text='Land Area in Bigha')),
                ('kattha', models.IntegerField(default=0, help_text='Kattha')),
                ('katthaToSqFeet', models.IntegerField(choices=[(720, 'Choti'), (1020, 'Badi')], default=1020, help_text='Kattha To Sq. Feet')),
                ('area', models.IntegerField(default=0, help_text='Area in Acre')),
                ('season', models.CharField(choices=[('FR', 'Spring'), ('SO', 'Summer'), ('JR', 'Autumn'), ('SR', 'Winter')], default='SO', max_length=2)),
                ('crop', models.CharField(choices=[('BIGO', 'Bitter Gourd'), ('TOMA', 'Tomato'), ('WATM', 'Water Melon'), ('MIRC', 'Green Chilli'), ('KHIR', 'Cucumber')], default='MIRC', max_length=4)),
                ('seeding', models.CharField(choices=[('SE', 'Seed'), ('SI', 'Seedling')], default='SI', max_length=2)),
                ('seeding_date', models.DateField(help_text='Date of seeding')),
                ('fertigation_plan', models.TextField(help_text='Fertigation Plan')),
                ('plant_protection_plan', models.TextField(help_text='Plant Protection Plan')),
                ('weeding_plan', models.TextField(help_text='Weeding Plan')),
                ('labour_planning', models.TextField(help_text='Labour Management Plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Crop Plan',
                'verbose_name_plural': 'Crop Plans',
            },
        ),
    ]
