# Generated by Django 3.1.2 on 2021-01-13 03:25

import crop_planning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(help_text='Name of Crop', max_length=30)),
                ('crop_image', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d ', validators=[crop_planning.models.validate_image], verbose_name='Crop Image')),
                ('sticky', models.BooleanField(default=False)),
                ('seed_check', models.BooleanField(default=True)),
                ('seedling_check', models.BooleanField(default=False)),
                ('mulch_check', models.BooleanField(default=True)),
                ('alan_check', models.BooleanField(default=True)),
                ('stake_check', models.BooleanField(default=True)),
                ('crop_cover_check', models.BooleanField(default=True)),
                ('gobar_check', models.BooleanField(default=True)),
                ('vermi_check', models.BooleanField(default=True)),
                ('fertiliz_bas_check', models.BooleanField(default=True)),
                ('fertiliz_ws_check', models.BooleanField(default=True)),
                ('marketing_check', models.BooleanField(default=True)),
                ('management_check', models.BooleanField(default=True)),
                ('lease_check', models.BooleanField(default=True)),
                ('miscell_check', models.BooleanField(default=True)),
                ('num_plants_acre', models.IntegerField(default=0)),
                ('prod_per_plant_min', models.IntegerField(default=0, help_text='in Kgs')),
                ('prod_per_plant_max', models.IntegerField(default=0, help_text='in Kgs')),
                ('prod_per_acre_min', models.IntegerField(default=0, help_text='in Kgs')),
                ('prod_per_acre_max', models.IntegerField(default=0, help_text='in Kgs')),
                ('sell_price_min', models.IntegerField(default=0)),
                ('sell_price_max', models.IntegerField(default=0)),
                ('crop_duration', models.IntegerField(default=6, help_text='Duration in month')),
                ('seed_cost', models.IntegerField(default=0)),
                ('per_plant_cost', models.IntegerField(default=0)),
                ('vermi_compost_cost', models.IntegerField(default=0)),
                ('plantation_cost', models.IntegerField(default=0)),
                ('fertilizer_bas_cost', models.IntegerField(default=0)),
                ('fertilizer_ws_cost', models.IntegerField(default=0)),
                ('pesticide_cost', models.IntegerField(default=0)),
                ('irrigation_cost', models.IntegerField(default=0)),
                ('marketing_and_harvesting_cost', models.IntegerField(default=0)),
                ('gobar_cost', models.IntegerField(default=0, help_text='Yearly Cost')),
                ('ploughing_bed_cost', models.IntegerField(default=0)),
                ('mulch_cost', models.IntegerField(default=0)),
                ('mulch_labour_cost', models.IntegerField(default=0)),
                ('weeding_cost', models.IntegerField(default=0)),
                ('alan_cost', models.IntegerField(default=0)),
                ('wire_stake', models.IntegerField(default=0)),
                ('wire_thin_tant', models.IntegerField(default=0)),
                ('stake_labour_cost', models.IntegerField(default=0)),
                ('wire_cost', models.IntegerField(default=0)),
                ('wire_recov_duration', models.IntegerField(default=48, help_text='In Months')),
                ('crop_cover', models.IntegerField(default=0)),
                ('labour_crop_cover', models.IntegerField(default=0)),
                ('land_lease_cost', models.IntegerField(default=0, help_text='Land lease per acre cost in inr per year')),
                ('plant_guarding_maintenance_cost', models.IntegerField(default=0)),
                ('management_cost', models.IntegerField(default=0)),
                ('miscell_cost', models.IntegerField(default=0)),
            ],
        ),
    ]
