# Generated by Django 3.1.2 on 2021-01-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_planning', '0002_cropbudget'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropbudget',
            name='crop_slug',
            field=models.SlugField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
