# Generated by Django 3.1.2 on 2021-01-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_planning', '0004_auto_20210113_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropbudget',
            name='per_plant_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cropbudget',
            name='prod_per_acre_max',
            field=models.FloatField(default=0, help_text='in Kgs'),
        ),
        migrations.AlterField(
            model_name='cropbudget',
            name='prod_per_acre_min',
            field=models.FloatField(default=0, help_text='in Kgs'),
        ),
        migrations.AlterField(
            model_name='cropbudget',
            name='prod_per_plant_max',
            field=models.FloatField(default=0, help_text='in Kgs'),
        ),
        migrations.AlterField(
            model_name='cropbudget',
            name='prod_per_plant_min',
            field=models.FloatField(default=0, help_text='in Kgs'),
        ),
        migrations.AlterField(
            model_name='cropbudget',
            name='seed_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cropbudget',
            name='sell_price_max',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cropbudget',
            name='sell_price_min',
            field=models.FloatField(default=0),
        ),
    ]
