# Generated by Django 3.1.2 on 2021-01-13 19:39

import crop_planning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_planning', '0005_auto_20210113_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cropbudget',
            old_name='wire_recov_duration',
            new_name='crop_cover_wire_recov_duration',
        ),
        migrations.RemoveField(
            model_name='cropbudget',
            name='wire_cost',
        ),
        migrations.AddField(
            model_name='cropbudget',
            name='crop_cover_wire_cost',
            field=models.IntegerField(default=0, help_text='Yearly Cost'),
        ),
        migrations.AlterField(
            model_name='cropbudget',
            name='alan_cost',
            field=models.IntegerField(default=0, help_text='Yearly Cost'),
        ),
        migrations.AlterField(
            model_name='cropbudget',
            name='crop_cover',
            field=models.IntegerField(default=0, help_text='Yearly Cost for Crop Cover'),
        ),
        migrations.AlterField(
            model_name='cropbudget',
            name='crop_duration',
            field=models.IntegerField(default=6, help_text='Duration in months'),
        ),
        migrations.AlterField(
            model_name='cropbudget',
            name='crop_image',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d', validators=[crop_planning.models.validate_image], verbose_name='Crop Image'),
        ),
        migrations.AlterField(
            model_name='cropbudget',
            name='fertilizer_bas_cost',
            field=models.IntegerField(default=0, help_text='Basal Dose Fertilizer Cost per Acre'),
        ),
        migrations.AlterField(
            model_name='cropbudget',
            name='fertilizer_ws_cost',
            field=models.IntegerField(default=0, help_text='Water Soluble Fertilizer Cost per Acre'),
        ),
        migrations.AlterField(
            model_name='cropbudget',
            name='irrigation_cost',
            field=models.IntegerField(default=0, help_text='Cost per Acre'),
        ),
        migrations.AlterField(
            model_name='cropbudget',
            name='labour_crop_cover',
            field=models.IntegerField(default=0, help_text='Yearly Cost'),
        ),
        migrations.AlterField(
            model_name='cropbudget',
            name='land_lease_cost',
            field=models.IntegerField(default=0, help_text='Land lease per acre cost in INR per year'),
        ),
        migrations.AlterField(
            model_name='cropbudget',
            name='management_cost',
            field=models.IntegerField(default=0, help_text='Monthly Cost in INR'),
        ),
        migrations.AlterField(
            model_name='cropbudget',
            name='marketing_and_harvesting_cost',
            field=models.IntegerField(default=0, help_text='Cost for Crop Cycle'),
        ),
        migrations.AlterField(
            model_name='cropbudget',
            name='miscell_cost',
            field=models.IntegerField(default=0, help_text='Cost in INR for crop cycle'),
        ),
        migrations.AlterField(
            model_name='cropbudget',
            name='mulch_cost',
            field=models.IntegerField(default=0, help_text='Yearly Cost'),
        ),
        migrations.AlterField(
            model_name='cropbudget',
            name='mulch_labour_cost',
            field=models.IntegerField(default=0, help_text='Yearly Cost'),
        ),
        migrations.AlterField(
            model_name='cropbudget',
            name='per_plant_cost',
            field=models.FloatField(default=0, help_text='Rs. per plant'),
        ),
        migrations.AlterField(
            model_name='cropbudget',
            name='pesticide_cost',
            field=models.IntegerField(default=0, help_text='Cost per Acre'),
        ),
        migrations.AlterField(
            model_name='cropbudget',
            name='plant_guarding_maintenance_cost',
            field=models.IntegerField(default=0, help_text='Monthly Cost in INR'),
        ),
        migrations.AlterField(
            model_name='cropbudget',
            name='plantation_cost',
            field=models.IntegerField(default=0, help_text='Cost per Acre'),
        ),
        migrations.AlterField(
            model_name='cropbudget',
            name='ploughing_bed_cost',
            field=models.IntegerField(default=0, help_text='Yearly Cost'),
        ),
        migrations.AlterField(
            model_name='cropbudget',
            name='seed_cost',
            field=models.FloatField(default=0, help_text='Seed Cost per Acre'),
        ),
        migrations.AlterField(
            model_name='cropbudget',
            name='sell_price_max',
            field=models.FloatField(default=0, help_text='Rs. per Kg'),
        ),
        migrations.AlterField(
            model_name='cropbudget',
            name='sell_price_min',
            field=models.FloatField(default=0, help_text='Rs. per Kg'),
        ),
        migrations.AlterField(
            model_name='cropbudget',
            name='stake_labour_cost',
            field=models.IntegerField(default=0, help_text='Yearly Cost'),
        ),
        migrations.AlterField(
            model_name='cropbudget',
            name='vermi_compost_cost',
            field=models.IntegerField(default=0, help_text='Cost per Acre'),
        ),
        migrations.AlterField(
            model_name='cropbudget',
            name='weeding_cost',
            field=models.IntegerField(default=0, help_text='Yearly Cost'),
        ),
        migrations.AlterField(
            model_name='cropbudget',
            name='wire_stake',
            field=models.IntegerField(default=0, help_text='Yearly Cost'),
        ),
        migrations.AlterField(
            model_name='cropbudget',
            name='wire_thin_tant',
            field=models.IntegerField(default=0, help_text='Yearly Cost'),
        ),
    ]
