# Generated by Django 3.1.2 on 2021-01-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_planning', '0006_auto_20210114_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropbudget',
            name='crop_cover_wire_cost',
        ),
        migrations.RemoveField(
            model_name='cropbudget',
            name='crop_cover_wire_recov_duration',
        ),
        migrations.AddField(
            model_name='cropbudget',
            name='wire_cost',
            field=models.IntegerField(default=0, help_text='Cost for Crop Cover Structure Wire'),
        ),
        migrations.AddField(
            model_name='cropbudget',
            name='wire_recov_duration',
            field=models.IntegerField(default=48, help_text='Crop Cover Structure Wire Recovery period In Months'),
        ),
    ]
