# Generated by Django 3.1.2 on 2021-01-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop_planning', '0007_auto_20210114_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropbudget',
            name='prod_per_plant_av',
            field=models.BooleanField(default=True),
        ),
    ]
