# Generated by Django 3.1.2 on 2020-12-24 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import farm_management.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Farm')),
                ('address', models.CharField(blank=True, max_length=70, verbose_name='Address')),
                ('notes', models.TextField(blank=True, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d ', validators=[farm_management.models.validate_image], verbose_name='Farm Image')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d ', validators=[farm_management.models.validate_image], verbose_name='Farm Image')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farm', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farm',
                'verbose_name_plural': 'Farms',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='Location')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d ', validators=[farm_management.models.validate_image], verbose_name='Location Image')),
                ('notes', models.TextField(blank=True, null=True)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farm_management.farm', verbose_name='Farm')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Sensor_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('pH', models.CharField(default='', help_text='pH value(0-14) ', max_length=3)),
                ('Moisture', models.CharField(default='', help_text='Moisture Value ', max_length=6)),
                ('Humidity', models.CharField(default='', help_text='Humidity Value ', max_length=4)),
                ('Temperature', models.CharField(default='', help_text='Temperature in degree C ', max_length=4)),
                ('Light', models.CharField(default='', help_text='Light value ', max_length=4)),
                ('Co2_level', models.CharField(default='', help_text='Carbon Dioxide(Co2) value ', max_length=4)),
                ('Wind', models.CharField(default='', help_text='Wind data ', max_length=4)),
                ('SunTracking', models.CharField(default='', help_text='Sun Tracking ', max_length=8)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farm_management.location', verbose_name='Location')),
            ],
        ),
    ]
