# Generated by Django 3.1.2 on 2020-12-24 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='user',
        ),
    ]
