# Generated by Django 3.1.2 on 2020-12-24 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farm_management', '0002_remove_farm_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='farm', to=settings.AUTH_USER_MODEL),
        ),
    ]
