# Generated by Django 3.1.2 on 2020-12-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0005_auto_20201225_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='farm_owner',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Farm Owner'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='farm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Farm'),
        ),
    ]
