# Generated by Django 3.1.2 on 2020-12-25 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farm_management', '0006_auto_20201225_0244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farm',
            options={'permissions': (('manage_farm', 'Manage Farm'),), 'verbose_name': 'Farm', 'verbose_name_plural': 'Farms'},
        ),
        migrations.AlterModelOptions(
            name='sensor_data',
            options={'verbose_name': 'Sensor_Da', 'verbose_name_plural': 'Sensor_Das'},
        ),
        migrations.AlterField(
            model_name='farm',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='user',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensor_data',
            name='Co2_level',
            field=models.CharField(blank=True, default='', help_text='Carbon Dioxide(Co2) value ', max_length=4),
        ),
        migrations.AlterField(
            model_name='sensor_data',
            name='Humidity',
            field=models.CharField(blank=True, default='', help_text='Humidity Value ', max_length=4),
        ),
        migrations.AlterField(
            model_name='sensor_data',
            name='Light',
            field=models.CharField(blank=True, default='', help_text='Light value ', max_length=4),
        ),
        migrations.AlterField(
            model_name='sensor_data',
            name='Moisture',
            field=models.CharField(blank=True, default='', help_text='Moisture Value ', max_length=6),
        ),
        migrations.AlterField(
            model_name='sensor_data',
            name='SunTracking',
            field=models.CharField(blank=True, default='', help_text='Sun Tracking ', max_length=8),
        ),
        migrations.AlterField(
            model_name='sensor_data',
            name='Temperature',
            field=models.CharField(blank=True, default='', help_text='Temperature in degree C ', max_length=4),
        ),
        migrations.AlterField(
            model_name='sensor_data',
            name='Wind',
            field=models.CharField(blank=True, default='', help_text='Wind data ', max_length=4),
        ),
        migrations.AlterField(
            model_name='sensor_data',
            name='pH',
            field=models.CharField(blank=True, default='', help_text='pH value(0-14) ', max_length=3),
        ),
    ]
