# Generated by Django 3.1.2 on 2020-12-26 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import farm_management.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farm_management', '0008_auto_20201225_2319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farm',
            options={'permissions': (('manage_farm', 'Manage Farm'),), 'verbose_name': 'Plot', 'verbose_name_plural': 'Plots'},
        ),
        migrations.AlterField(
            model_name='farm',
            name='farm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Plot'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='farm_owner',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Farmer'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d ', validators=[farm_management.models.validate_image], verbose_name='Plot Image'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d ', validators=[farm_management.models.validate_image], verbose_name='Plot Image'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='location',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farm_management.farm', verbose_name='Plot'),
        ),
    ]
