# Generated by Django 3.1.2 on 2020-12-27 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0009_auto_20201226_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor_data',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farm_management.farm', verbose_name='Plot'),
        ),
    ]
