# Generated by Django 3.1.2 on 2020-12-27 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0010_sensor_data_farm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor_data',
            name='farm',
        ),
    ]
