# Generated by Django 3.1.2 on 2020-12-27 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0011_remove_sensor_data_farm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farm',
            options={'permissions': (('monitor_data', 'Monitor Data'),), 'verbose_name': 'Plot', 'verbose_name_plural': 'Plots'},
        ),
    ]
